name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop, 'release/*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri dependencies on Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --run # Use --run to prevent Vitest from watching for changes
