name: Release

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tauri-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
      # For code signing (optional; set up later)
      #TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      #TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install JS deps
        run: npm ci

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            ./src-tauri -> target

      - name: Linux deps (only on Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev \
            librsvg2-dev patchelf pkg-config build-essential

      - name: Build & bundle Tauri app
        uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: npm run tauri
          args: --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optionally upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: |
            src-tauri/target/**/bundle/**/*.deb
            src-tauri/target/**/bundle/**/*.AppImage
            src-tauri/target/**/bundle/**/*.dmg
            src-tauri/target/**/bundle/**/*.msi
            src-tauri/target/**/bundle/**/*.zip
          if-no-files-found: ignore
